#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-RSS-Parser
version:      2.13
version_from: lib/XML/RSS/Parser.pm
installdirs:  site
requires:
    Class::XPath:                  1.4
    XML::Parser:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
